spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notes
    username: 
    password: 
    
  jpa:
    show-sql: true 
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

token:
  expiration_time: 864000000  
  secret: jfhhjrfbiwoocife
